stages:
  - build
  - package

variables:
  QT_VERSION: "6.5.0"
  ARTIFACT_NAME: "la-calc-macos"

build_macos:
  stage: build
  tags:
    - macos  # Требуется macOS-раннер с тегом 'macos'
  script:
    - brew update
    - brew install qt@6
    - export PATH="/usr/local/opt/qt@6/bin:$PATH"
    - cd app
    - qmake6 la-calc.pro -spec macx-clang CONFIG+=release
    - make -j$(sysctl -n hw.ncpu)
    - mkdir -p ../la-calc.app/Contents/{MacOS,Resources}
    - cp la-calc ../la-calc.app/Contents/MacOS/
    - cp ../README.md ../la-calc.app/Contents/Resources/
  artifacts:
    paths:
      - la-calc.app/

package_dmg:
  stage: package
  tags:
    - macos
  script:
    - hdiutil create -volname "Linear Algebra Calculator"
      -srcfolder la-calc.app
      -ov -format UDZO la-calc.dmg
  artifacts:
    paths:
      - la-calc.dmg
