name: Build and Package
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Homebrew dependencies
      run: |
        brew update
        brew install qt@6 libomp
        brew link --force qt@6

    - name: Configure environment
      shell: bash
      run: |
        echo "QT_PATH=$(brew --prefix qt@6)" >> $GITHUB_ENV
        echo "$HOME/brew/bin" >> $GITHUB_PATH

    - name: Build application
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.0
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release --parallel 4
        mkdir -p ../dist
        cp -r la-calc.app ../dist/

    - name: Deploy Qt libraries
      run: |
        cd dist/la-calc.app/Contents/MacOS
        /usr/local/opt/qt@6/bin/macdeployqt la-calc.app \
          -verbose=3 \
          -always-overwrite \
          -no-strip

    - name: Verify application bundle
      run: |
        echo "Application size:"
        du -sh dist/la-calc.app
        
        echo "Bundle structure:"
        ls -lR dist/la-calc.app

    - name: Create DMG package
      timeout-minutes: 15
      run: |
        # Clean previous artifacts
        rm -f dist/la-calc.dmg || true
        
        # Create disk image with verbose output
        hdiutil create -fs HFS+ \
          -volname "Linear Algebra Calculator" \
          -srcfolder dist/la-calc.app \
          -format UDZO \
          -ov \
          -verbose \
          dist/la-calc.dmg

        # Verify resulting DMG
        ls -lh dist/la-calc.dmg
        hdiutil verify dist/la-calc.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: la-calc-macos
        path: |
          dist/la-calc.dmg
          dist/la-calc.app
