name: Build and Package
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install qt@6
        echo "PATH=$(brew --prefix qt@6)/bin:$PATH" >> $GITHUB_ENV

    - name: Prepare build directory
      run: |
        mkdir -p app/build
        cd app/build
        qmake6 -makefile -spec macx-clang "CONFIG += release" ../la-calc.pro

    - name: Build application
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.0
      run: |
        cd app/build
        make -j4
        mkdir -p ../../dist
        cp -r la-calc.app ../../dist/

    - name: Deploy Qt libraries
      run: |
        export PATH=$(brew --prefix qt@6)/bin:$PATH
        macdeployqt ../../dist/la-calc.app \
          -verbose=3 \
          -always-overwrite \
          -no-strip

    # Остальные шаги остаются без изменений
    - name: Verify bundle
      run: |
        echo "Application structure:"
        find dist/la-calc.app -print
        echo "Size:"
        du -sh dist/la-calc.app

    - name: Code Signing
      run: |
        codesign --deep --force --verify --verbose \
        --sign "-" \
        dist/la-calc.app

    - name: Create DMG
      timeout-minutes: 15
      run: |
        rm -f dist/la-calc.dmg || true
        
        hdiutil create -fs HFS+ \
          -volname "Linear Algebra Calculator" \
          -srcfolder dist/la-calc.app \
          -format UDZO \
          -ov \
          -verbose \
          dist/la-calc.dmg

        hdiutil verify dist/la-calc.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: la-calc-macos
        path: dist/la-calc.dmg
