name: Build and Package
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install qt@6 jpeg-turbo libtiff webp
        echo "QT_PATH=$(brew --prefix qt@6)" >> $GITHUB_ENV
        echo "PATH=$QT_PATH/bin:$PATH" >> $GITHUB_ENV

    - name: Prepare build directory
      run: |
        mkdir -p app/build
        cd app/build
        qmake6 -makefile -spec macx-clang "CONFIG += release" ../la-calc.pro

    - name: Build application
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.0
      run: |
        cd app/build
        make -j4

    - name: Deploy Qt libraries
      run: |
        export QT_PATH=${{ env.QT_PATH }}
        macdeployqt app/build/la-calc.app \
          -verbose=3 \
          -always-overwrite \
          -no-strip \
          -libpath=$QT_PATH/lib \
          -qmldir=$QT_PATH/qml

        # Проверка структуры бандла
        ls -lR app/build/la-calc.app/Contents/Frameworks
        du -sh app/build/la-calc.app

    - name: Create DMG
      run: |
        mkdir -p dist
        hdiutil create -fs HFS+ \
          -volname "Linear Algebra Calculator" \
          -srcfolder app/build/la-calc.app \
          -format UDZO \
          -ov \
          dist/la-calc.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: la-calc-macos
        path: dist/la-calc.dmg
