name: Build macOS App

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Qt
      uses: actions/cache@v3
      with:
        path: /usr/local/Cellar/qt@6
        key: ${{ runner.os }}-qt6-${{ hashFiles('app/la-calc.pro') }}

    - name: Install Qt 6
      if: steps.Cache.outputs.cache-hit != 'true'
      run: |
        brew update
        brew install qt@6 qttools
        echo "QT_PATH=/usr/local/opt/qt@6" >> $GITHUB_ENV

    - name: Build application
      run: |
        cd app
        qmake6 la-calc.pro -spec macx-clang CONFIG+=release
        make -j$(sysctl -n hw.ncpu)
        mkdir -p ../dist
        cp -R la-calc.app ../dist/

    - name: Deploy Qt dependencies
      run: |
        export PATH="/usr/local/opt/qt@6/bin:$PATH"
        macdeployqt ../dist/la-calc.app -verbose=3

    - name: Create DMG package
      run: |
        hdiutil create -volname "Linear Algebra Calculator" \
          -srcfolder dist/la-calc.app \
          -ov -format UDZO dist/la-calc.dmg

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name:
