name: Build and Package
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install qt@6 jpeg-turbo libtiff webp graphite2
        echo "QT_PATH=$(brew --prefix qt@6)" >> $GITHUB_ENV
        echo "PATH=$QT_PATH/bin:$PATH" >> $GITHUB_ENV

    - name: Prepare build directory
      run: |
        mkdir -p app/build
        cd app/build
        qmake6 -makefile -spec macx-clang "CONFIG += release" ../la-calc.pro

    - name: Build application
      env:
        MACOSX_DEPRECATED: 1  # Для совместимости
        MACOSX_DEPLOYMENT_TARGET: 11.0
      run: |
        cd app/build
        make -j4

    - name: Deploy Qt libraries
      run: |
        export QT_PATH=${{ env.QT_PATH }}
        macdeployqt app/build
