name: Build macOS App

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 40

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean environment
      run: |
        brew uninstall --ignore-dependencies qt || true
        rm -rf /opt/homebrew/opt/qt*
        brew cleanup

    - name: Install Qt
      run: |
        brew update
        brew install qt
        echo "QT_PATH=/opt/homebrew/opt/qt" >> $GITHUB_ENV
        echo "PATH=$PATH:/opt/homebrew/opt/qt/bin" >> $GITHUB_ENV
        
        # Проверка macdeployqt
        if [ ! -f /opt/homebrew/opt/qt/bin/macdeployqt ]; then
          echo "❌ macdeployqt not found at:"
          find /opt/homebrew -name macdeployqt
          exit 1
        fi

    - name: Build application
      run: |
        cd app
        /opt/homebrew/opt/qt/bin/qmake la-calc.pro -spec macx-clang CONFIG+=release
        make -j$(sysctl -n hw.ncpu)
        
        if [ ! -f la-calc.app/Contents/MacOS/la-calc ]; then
          echo "❌ Binary not found!"
          exit 1
        fi

    - name: Deploy dependencies
      run: |
        mkdir -p dist
        cp -R app/la-calc.app dist/
        /opt/homebrew/opt/qt/bin/macdeployqt dist/la-calc.app -verbose=3
        
        if [ ! -d dist/la-calc.app/Contents/Frameworks ]; then
          echo "❌ Frameworks not deployed!"
          exit 1
        fi

    - name: Create DMG
      run: |
        hdiutil create -fs HFS+ \
          -volname "Linear Algebra Calculator" \
          -srcfolder dist/la-calc.app \
          -ov -format UDZO dist/la-calc.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: la-calc-macos
        path: dist/la-calc.dmg
