name: Build and Package
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install qt@6
        brew link --force qt@6
        echo "QT_BIN_PATH=$(brew --prefix qt@6)/bin" >> $GITHUB_PATH

    - name: Prepare build directory
      run: |
        mkdir -p app/build
        cd app && qmake -makefile -spec macx-clang "CONFIG += release" la-calc.pro

    - name: Build application
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.0
      run: |
        cd app/build
        make -j4
        
        # Create dist directory
        mkdir -p ../../dist
        cp -r release/la-calc.app ../../dist/

    - name: Deploy Qt libraries
      run: |
        $(brew --prefix qt@6)/bin/macdeployqt dist/la-calc.app \
          -verbose=3 \
          -always-overwrite \
          -no-strip \
          -qmldir=app

    - name: Verify bundle
      run: |
        echo "Application structure:"
        find dist/la-calc.app -print
        echo "Size:"
        du -sh dist/la-calc.app

    - name: Create DMG
      timeout-minutes: 15
      run: |
        rm -f dist/la-calc.dmg || true
        
        hdiutil create -fs HFS+ \
          -volname "Linear Algebra Calculator" \
          -srcfolder dist/la-calc.app \
          -format UDZO \
          -ov \
          -verbose \
          dist/la-calc.dmg

        hdiutil verify dist/la-calc.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: la-calc-macos
        path: dist/la-calc.dmg
