name: Build and Package (qmake)
on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt and dependencies
      run: |
        # Установка Qt 6 и зависимостей
        brew update
        brew install qt@6
        brew link --force qt@6
        
        # Проверяем пути
        echo "QMAKE_PATH=$(which qmake)" >> $GITHUB_ENV
        echo "QT_BIN_PATH=$(brew --prefix qt@6)/bin" >> $GITHUB_PATH

    - name: Build application
      env:
        MACOSX_DEPLOYMENT_TARGET: 11.0
      run: |
        # Генерируем Makefile
        qmake -spec macx-clang -config release "CONFIG += release" YOUR_PROJECT.pro
        
        # Сборка
        make -j4
        
        # Создаем папку dist
        mkdir -p dist
        cp -r release/YOUR_APP.app dist/

    - name: Deploy Qt libraries
      run: |
        # Развертывание зависимостей
        $(brew --prefix qt@6)/bin/macdeployqt dist/YOUR_APP.app \
          -verbose=3 \
          -always-overwrite \
          -no-strip

    - name: Create DMG package
      timeout-minutes: 15
      run: |
        # Очистка предыдущих образов
        rm -f dist/YOUR_APP.dmg || true
        
        # Создание DMG
        hdiutil create -fs HFS+ \
          -volname "Your App Name" \
          -srcfolder dist/YOUR_APP.app \
          -format UDZO \
          -ov \
          -verbose \
          dist/YOUR_APP.dmg

        # Проверка результата
        ls -lh dist/YOUR_APP.dmg
        hdiutil verify dist/YOUR_APP.dmg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: your-app-macos
        path: dist/YOUR_APP.dmg
